app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    # Page Routes
    from .routes.account import account_bp
    from .routes.config import config_bp
    from .routes.createAccount import createAccount_bp
    from .routes.errorLog import errorLog_bp
    from .routes.index import index_bp
    from .routes.setLoader import setLoader_bp

    # API Routes
    from .routes.api.copyToAccount import copyToAccount_bp
    from .routes.api.deleteSet import deleteSet_bp
    from .routes.api.getProfileSets import getProfileSets_bp
    from .routes.api.uploadSets import uploadSets_bp
    from .routes.api.downloadCSV import downloadCSV_bp
    from .routes.api.getDrawdownGraph import getDrawdownGraph_bp



    app.register_blueprint(account_bp)
    app.register_blueprint(config_bp)
    app.register_blueprint(createAccount_bp)
    app.register_blueprint(errorLog_bp)
    app.register_blueprint(index_bp)
    app.register_blueprint(setLoader_bp)

    app.register_blueprint(copyToAccount_bp)
    app.register_blueprint(deleteSet_bp)
    app.register_blueprint(getProfileSets_bp)
    app.register_blueprint(uploadSets_bp)
    app.register_blueprint(downloadCSV_bp)
    app.register_blueprint(getDrawdownGraph_bp)

    return app

app/routes/account.py
from flask import Blueprint, render_template
from scripts.database.getAccounts import getAccounts
from scripts.database.getDrawdownGraphData import getDrawdownGraphData
from scripts.database.getEquityGraphData import getEquityGraphData
from scripts.database.getFilterData import getFilterData
from scripts.database.getFrontendSets import getFrontendSets

account_bp = Blueprint('account', __name__)

@account_bp.route('/<account_id>')
def account(account_id):
    sets = getFrontendSets(account_id)
    slaveAccounts = []
    accounts = getAccounts()
    accountProfit = 0
    accountMaxDrawdown = 0
    accountAverageDrawdown = 0
    testSets = len(sets)
    daysLive = 0
    for set in sets:
        accountProfit += set["stats"]["profit"]
        try:
            accountMaxDrawdown += set["stats"]["maxDrawdown"]
            accountAverageDrawdown+= set["stats"]["avgDrawdown"]
        except:
            pass
        if set["stats"]["daysLive"] > daysLive:
            daysLive = set["stats"]["daysLive"]
    for account in accounts:
        if account["type"] == "slave":
            slaveAccounts.append(account["login"])
    if len(sets) != 0:
        return render_template('account.html', account_id = {"account_id": account_id}, sets=sets, drawdownData = getDrawdownGraphData(account_id, "15m"), equityData = getDrawdownGraphData(account_id, "1h"), filterData = getFilterData(account_id), accounts=slaveAccounts, accountProfit=round(accountProfit,2), accountDrawdown=round(accountMaxDrawdown,2), testSets=testSets, accountAverageDrawdown=round(accountAverageDrawdown, 2))
    else:
        return render_template('empty_account.html')

app/routes/config.py
import os
from flask import Blueprint, json, redirect, render_template, request, url_for

config_bp = Blueprint('config', __name__)
user_profile = os.environ['USERPROFILE']
configFile = os.path.join(user_profile, 'AppData', 'Local', 'Mt5TrackerDatabase', 'config.json')

@config_bp.route('/config', methods=['GET', 'POST'])
def config():
    if request.method == 'POST':
        powName = request.form['powName']
        powAPIKey = request.form['powAPIKey']
        symbolSuffix = request.form['symbolSuffix']
        config = {"powName": powName, "powAPIKey": powAPIKey,  "symbolSuffix": symbolSuffix}
        save_config(config)
        return redirect(url_for('config.config'))

    config = load_config()
    return render_template('config.html', config=config)

def save_config(config):
    with open(configFile, 'w') as f:
        json.dump(config, f)

def load_config():
    if os.path.exists(configFile):
        with open(configFile, 'r') as f:
            return json.load(f)
    return {"powName": "", "powAPIKey": "", "symbolSuffix": ""}

app/routes/createAccount.py
from flask import Blueprint, redirect, render_template, request, url_for
from scripts.database.createAccount import createAccount

createAccount_bp = Blueprint('create_account', __name__)

@createAccount_bp.route('/create_account', methods=['GET', 'POST'])
def create_account():
    if request.method == 'POST':
        if request.form['type'] == "master":
            status = "initializing"
        elif request.form['type'] == "slave":
            status = "waiting for master"
        else:
            status = "error"
        account_data = {
            'terminalFilePath': request.form.getlist('terminalFilePath'),
            'status': "initializing"
        }
        for key, val in request.form.items():
            if key == "terminalFilePath":
                pass
            else:
                account_data[key] = val
        print(account_data)
        createAccount(account_data)
        return redirect(url_for('index.index'))
    return render_template('createAccount.html')

app/routes/errorLog.py
from flask import Blueprint, render_template
from scripts.database.getErrorLog import getErrorLog

errorLog_bp = Blueprint('errorLog', __name__)

@errorLog_bp.route('/error_log')
def error_log():
    return render_template('error_log.html', errors=getErrorLog())

app/routes/index.py
from flask import Blueprint, render_template
from scripts.database.getAccounts import getAccounts
from scripts import runTracker

index_bp = Blueprint('index', __name__)

@index_bp.route('/')
def index():
    runTracker.run()
    return render_template('index.html', accounts=getAccounts())

app/routes/setLoader.py
from flask import Blueprint, render_template
from scripts.database.getAccounts import getAccounts
from scripts.database.getProfiles import getProfiles

setLoader_bp = Blueprint('setLoader', __name__)

@setLoader_bp.route('/set_loader')
def set_loader():
    accounts = getAccounts()
    accountIDs = []
    profiles = {}
    for account in accounts:
        accountIDs.append(account["login"])
        profiles[account["login"]] = getProfiles(account)
    return render_template('uploadSets.html', sets=[], accounts=accountIDs, profiles=profiles)

app/templates/account.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
			rel="stylesheet"
		/>
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='test.css') }}"
		/>
		<script src="{{url_for('static', filename='plotly-2.32.0.min.js')}}"></script>
		<script>
			var setsData = {{ sets | tojson }};
			var graphData = {{ drawdownData | tojson }};
			var equityData = {{ equityData | tojson }};
			var filterData = {{ filterData | tojson }};
			var accounts = {{ accounts | tojson }};
			var accountProfit = {{ accountProfit }};
			var accountDrawdown = {{ accountDrawdown }};
			var accountAvgDrawdown = {{ accountAverageDrawdown }};
			var testSets = {{ testSets }};
			var account_id = {{ account_id | tojson }};

		</script>
		<title>POW Tracker - Tracker</title>
	</head>

	<body class="dark">
		<!-- Sidebar -->
		<div class="sidebar">
			<a href="#" class="logo">
				<i class="bx bx-code-alt"></i>
				<div class="logo-name"><span>POW</span>Tracker</div>

			</a>
			<ul class="side-menu">
				<li>
					<a href="/"><i class="bx bxs-dashboard"></i>Accounts</a>
				</li>
				<li class="active">
					<a href=""><i class="bx bx-store-alt"></i>Tracker</a>
				</li>
				<li>
					<a href="/set_loader"><i class="bx bx-analyse"></i>Set Loader</a>
				</li>
				<li>
					<a href="/config"><i class="bx bx-message-square-dots"></i>Config</a>
				</li>
				<li>
					<a href="/error_log"><i class="bx bx-group"></i>Error Log</a>
				</li>
			</ul>
			<ul class="side-menu">

			</ul>
		</div>
		<!-- End of Sidebar -->

		<!-- Main Content -->
		<div class="content">
			<!-- Navbar -->
			<nav>
				<i class="bx bx-menu"></i>
				<form action="#">
					<div class="form-input" style="display: none">
						<input type="search" placeholder="Search..." />
						<button class="search-btn" type="submit">
							<i class="bx bx-search"></i>
						</button>
					</div>
				</form>
				<input type="checkbox" id="theme-toggle" hidden />
				<label for="theme-toggle" class="theme-toggle"></label>
				<a href="#" class="notif">
					<i class="bx bx-bell"></i>
					<span class="count">12</span>
				</a>

			</nav>

			<!-- End of Navbar -->

			<main>
				<div class="header">
					<div class="left">
						<h1>Tracker</h1>
						<ul class="breadcrumb">
							<li><a href="#"> Accounts </a></li>
							/
							<li><a href="#" class="active">34534</a></li>
						</ul>
					</div>

					<div style="display: flex; justify-content: center; align-items: center; gap: 10px;">
						<button id="deleteSetButton" disabled class="button">Delete Set</button>
						<select id="accountSelect" class="button" disabled>
							<option value="">Copy to</option>
						</select>
						<a href="/set_loader"><button class="button">Add Set</button></a>
						<a id="downloadCSVButton" style="cursor: pointer;" class="report">
							<i class="bx bx-cloud-download"></i>
							<span>Download CSV</span>
						</a>
					</div>
				</div>

				<!-- Insights -->
				<ul class="insights">
					<li>
						<i class="bx bx-dollar-circle"></i>
						<span class="info">
							<h3 id="selectedProfit">{{ accountProfit }}</h3>
							<p>Total Profit</p>
						</span>
					</li>
					<li>
						<i class="bx bx-show-alt"></i>
						<span class="info">
							<h3 id="selectedMaxDrawdown">{{ accountDrawdown }}</h3>
							<p>Max Drawdown</p>
						</span>
					</li>
					<li>
						<i class="bx bx-line-chart"></i>
						<span class="info">
							<h3 id="selectedAvgDrawdown">{{ accountAverageDrawdown }}</h3>
							<p>Average Drawdown</p>
						</span>
					</li>
					<li>
						<i class="bx bx-calendar-check"></i>
						<span class="info">
							<h3 id="selectedSets">{{ testSets }}</h3>
							<p>Sets</p>
						</span>
					</li>
				</ul>
				<!-- End of Insights -->

				<div class="bottom-data">
					<div class="orders">
						<div class="header">
							<i class="bx bx-receipt"></i>
							<h3>Sets</h3>
							<i id="filterButton" class="bx bx-filter"></i>
							<i id="searchButton" class="bx bx-search"></i>
						</div>
						<div id="filters-container" class="filters-container" style="display: none;">
							<div class="table-filters">
								<div class="column-filters">
									<div class="quad-column">
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="setName"  data-column="0" checked> Set Name</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="magic" data-column="1" checked> Magic</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="profit" data-column="2" checked> Profit</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="trades" data-column="3" checked> Trades</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="avgTradeTime" data-column="16" > Avg Trade Time</label>
									</div>
									<div class="quad-column">
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="maxDrawdown" data-column="4" checked> Max Drawdown</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="avgDrawdown" data-column="5" checked> Average Drawdown</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="profitFactor" data-column="6" checked> Profit Factor</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="returnOnDrawdown" data-column="7" checked> Return on Drawdown</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="daysLive" data-column="17" checked> Days Live</label>
									</div>
									<div class="quad-column">
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="minLotSize" data-column="8" > Min Lot Size</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="maxLotSize" data-column="9" > Max Lot Size</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="avgLotSize" data-column="10" > Average Lot Size</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="winRate" data-column="11" checked> Win Rate</label>
									</div>
									<div class="quad-column">
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="wins" data-column="12" checked> Wins</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="losses" data-column="13" checked> Losses</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="minTradeTime" data-column="14" > Min Trade Time</label>
										<label class="column-toggle-container"><input type="checkbox" class="column-toggle" id="maxTradeTime" data-column="15" > Max Trade Time</label>
									</div>
								</div>
								<div style="display: flex; flex-direction: column; gap: 10px; align-items: center;">
									<div class="filter-section">
										<div class="quad-column">
											<div class="filter-group">
												<label for="max-drawdown">Min Profit</label>
												<div class="slider-container">
													<input type="range" id="min-profit" name="min-profit" min="0" max="100" value="50" oninput="updateSliderValue('min-profit')">
													<span id="min-profit-value">50</span>
												</div>
											</div>

											<div class="filter-group">
												<label for="max-drawdown">Max Drawdown</label>
												<div class="slider-container">
													<input type="range" id="max-drawdown" name="max-drawdown" min="0" max="100" value="50" oninput="updateSliderValue('max-drawdown')">
													<span id="max-drawdown-value">50</span>
												</div>
											</div>

											<div class="fi	lter-group">
												<label for="avg-drawdown">Max Average Drawdown</label>
												<div class="slider-container">
													<input type="range" id="avg-drawdown" name="avg-drawdown" min="0" max="100" value="50" oninput="updateSliderValue('avg-drawdown')">
													<span id="avg-drawdown-value">50</span>
												</div>
											</div>
										</div>
										<div class="quad-column">
											<div class="filter-group">
												<label for="profit-factor">Min Profit Factor</label>
												<div class="slider-container">
													<input type="range" id="profit-factor" name="profit-factor" min="0" max="100" value="50" oninput="updateSliderValue('profit-factor')">
													<span id="profit-factor-value">50</span>
												</div>
											</div>
											<div class="filter-group">
												<label for="return-drawdown">Min Return on Drawdown</label>
												<div class="slider-container">
													<input type="range" id="return-drawdown" name="return-drawdown" min="0" max="100" value="50" oninput="updateSliderValue('return-drawdown')">
													<span id="return-drawdown-value">50</span>
												</div>
											</div>
											<div class="filter-group">
												<label for="win-rate">Min Win Rate</label>
												<div class="slider-container">
													<input type="range" id="win-rate" name="win-rate" min="0" max="100" value="50" oninput="updateSliderValue('win-rate')">
													<span id="win-rate-value">50</span>
												</div>
											</div>
										</div>
										<div class="quad-column">
											<div class="filter-group">
												<label for="avg-trade-time">Max Avg Trade Time</label>
												<div class="slider-container">
													<input type="range" id="avg-trade-time" name="avg-trade-time" min="0" max="100" value="50" oninput="updateSliderValue('avg-trade-time')">
													<span id="avg-trade-time-value">50</span>
												</div>
											</div>
											<div class="filter-group">
												<label for="days-live">Min Trades</label>
												<div class="slider-container">
													<input type="range" id="min-trades" name="min-trades" min="0" max="100" value="50" oninput="updateSliderValue('min-trades')">
													<span id="min-trades-value">50</span>
												</div>
											</div>
											<div class="filter-group">
												<label for="days-live">Min Days Live</label>
												<div class="slider-container">
													<input type="range" id="min-days-live" name="min-days-live" min="0" max="100" value="50" oninput="updateSliderValue('min-days-live')">
													<span id="min-days-live-value">50</span>
												</div>
											</div>
										</div>

									</div>
									<button style="width: 20%;" class="button">Apply Filters</button>
								</div>

							</div>
						</div>
						<table id="data-table">
							<thead>
								<tr>
									<th id="setNameHeader">Set Name</th>
									<th id="magicHeader">Magic</th>
									<th id="profitHeader">Profit</th>
									<th id="tradesHeader">Trades</th>
									<th id="maxDrawdownHeader">Max Drawdown</th>
									<th id="avgDrawdownHeader">Average Drawdown</th>
									<th id="profitFactorHeader">Profit Factor</th>
									<th id="returnOnDrawdownHeader">Return on Drawdown</th>
									<th id="minLotSizeHeader">Min Lot Size</th>
									<th id="maxLotSizeHeader">Max Lot Size</th>
									<th id="avgLotSizeHeader">Average Lot Size</th>
									<th id="winRateHeader">Win Rate</th>
									<th id="winsHeader">Wins</th>
									<th id="lossesHeader">Losses</th>
									<th id="minTradeTimeHeader">Min Trade Time</th>
									<th id="maxTradeTimeHeader">Max Trade Time</th>
									<th id="avgTradeTimeHeader">Avg Trade Time</th>
									<th id="daysLiveHeader">Days Live</th>
								</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
					</div>
					<div class="graph-section">
						<select id="timeframeSelect" class="button" >
							<option value="10s">10s</option>
							<option value="30s">30s</option>
							<option value="1m">1m</option>
							<option value="5m">5m</option>
							<option value="10m">10m</option>
							<option value="15m" selected>15m</option>
							<option value="30m">30m</option>
							<option value="45m">45m</option>
							<option value="1h">1h</option>
							<option value="2h">2h</option>
							<option value="4h">4h</option>
							<option value="1D">1D</option>

						</select>
						<div id="drawdownGraph"></div>
						<div id="equityGraph" style="margin-top: 20px"></div>
					</div>

					<!-- End of Reminders-->
				</div>
			</main>
		</div>

		<script src={{url_for('static', filename='test.js')}}></script>
		<script src={{url_for('static', filename='script.js')}}></script>
		<script>
			function updateSliderValue(sliderId) {
				const slider = document.getElementById(sliderId);
				const valueSpan = document.getElementById(sliderId + "-value");
				valueSpan.textContent = slider.value;
			}
		</script>
	</body>
</html>

app/templates/config.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
			rel="stylesheet"
		/>
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='test.css') }}"
		/>
		<title>POW Tracker - Config</title>
	</head>

	<body class="dark">
		<!-- Sidebar -->
		<div class="sidebar">
			<a href="#" class="logo">
				<i class="bx bx-code-alt"></i>
				<div class="logo-name"><span>POW</span>Tracker</div>
			</a>
			<ul class="side-menu">
				<li>
					<a href="/"><i class="bx bxs-dashboard"></i>Accounts</a>
				</li>
				<li>
					<a href="/"><i class="bx bx-store-alt"></i>Tracker</a>
				</li>
				<li>
					<a href="/set_loader"><i class="bx bx-analyse"></i>Set Loader</a>
				</li>
				<li class="active">
					<a href="/config"><i class="bx bx-message-square-dots"></i>Config</a>
				</li>
				<li>
					<a href="/error_log"><i class="bx bx-group"></i>Error Log</a>
				</li>
			</ul>
			<ul class="side-menu"></ul>
		</div>
		<!-- End of Sidebar -->

		<!-- Main Content -->
		<div class="content">
			<!-- Navbar -->
			<nav>
				<i class="bx bx-menu"></i>
				<form action="#">
					<div class="form-input" style="display: none">
						<input type="search" placeholder="Search..." />
						<button class="search-btn" type="submit">
							<i class="bx bx-search"></i>
						</button>
					</div>
				</form>
				<input type="checkbox" id="theme-toggle" hidden />
				<label for="theme-toggle" class="theme-toggle"></label>
				<a href="#" class="notif">
					<i class="bx bx-bell"></i>
					<span class="count">12</span>
				</a>
			</nav>

			<!-- End of Navbar -->

			<main>
				<div class="header">
					<div class="left">
						<h1>Config</h1>
					</div>

					<div
						style="
							display: flex;
							justify-content: center;
							align-items: center;
							gap: 10px;
						"
					></div>
				</div>
				<form
					method="post"
					action="{{ url_for('config.config') }}"
					style="
						width: 100%;
						align-items: center;
						justify-content: center;
						display: flex;
						flex-direction: column;
						gap: 10px;
					"
				>
					<div class="form-group">
						<label style="color: var(--dark); margin-right: 10px" for="powName"
							>POW Name:</label
						>
						<input
							type="text"
							id="powName"
							class="upload-options"
							name="powName"
							value="{{ config.powName }}"
							required
						/>
					</div>
					<div class="form-group">
						<label
							style="color: var(--dark); margin-right: 10px"
							for="powAPIKey"
							>POW API Key:</label
						>
						<input
							type="text"
							id="powAPIKey"
							name="powAPIKey"
							value="{{ config.powAPIKey }}"
							required
						/>
					</div>
					<div class="form-group">
						<label
							style="color: var(--dark); margin-right: 10px"
							for="symbolSuffix"
							>Symbol Suffix:</label
						>
						<input
							type="text"
							id="symbolSuffix"
							name="symbolSuffix"
							value="{{ config.symbolSuffix }}"
						/>
					</div>
					<button type="submit">Save</button>
				</form>
			</main>
		</div>

		<script src="{{url_for('static', filename='test.js')}}"></script>
	</body>
</html>

app/templates/createAccount.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Create Account</title>
		<link
			href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
			rel="stylesheet"
		/>
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='createAccount.css') }}" />
			<link
			rel="stylesheet"
			href="{{ url_for('static', filename='test.css') }}" />
	</head>
	<body class="dark">
		<!-- Sidebar -->
		<div class="sidebar">
			<a href="#" class="logo">
				<i class="bx bx-code-alt"></i>
				<div class="logo-name"><span>POW</span>Tracker</div>
			</a>
			<ul class="side-menu">
				<li>
					<a href="/"><i class="bx bxs-dashboard"></i>Accounts</a>
				</li>
				<li>
					<a href="/"><i class="bx bx-store-alt"></i>Tracker</a>
				</li>
				<li>
					<a href="/set_loader"><i class="bx bx-analyse"></i>Set Loader</a>
				</li>
				<li>
					<a href="/config"><i class="bx bx-message-square-dots"></i>Config</a>
				</li>
				<li>
					<a href="/error_log"><i class="bx bx-group"></i>Error Log</a>
				</li>
			</ul>
			<ul class="side-menu"></ul>
		</div>
		<!-- End of Sidebar -->

		<!-- Main Content -->
		<div class="content">
			<!-- Navbar -->
			<nav>
				<i class="bx bx-menu"></i>
				<form action="#">
					<div class="form-input" style="display: none">
						<input type="search" placeholder="Search..." />
						<button class="search-btn" type="submit">
							<i class="bx bx-search"></i>
						</button>
					</div>
				</form>
				<input type="checkbox" id="theme-toggle" hidden />
				<label for="theme-toggle" class="theme-toggle"></label>
				<a href="#" class="notif">
					<i class="bx bx-bell"></i>
					<span class="count">12</span>
				</a>
			</nav>
		<main>
		<div class="container">
			<header>
				<h1>Create New Account</h1>
				<a href="{{ url_for('index.index') }}"
					><button>Back to Dashboard</button></a
				>
			</header>

			<section class="form-section">
				<form
					id="create-account-form"
					method="POST"
					action="{{ url_for('create_account.create_account') }}">
					<div class="form-group">
						<label for="name">Account Name:</label>
						<input type="text" id="name" name="name" required />
					</div>
					<div class="form-group">
						<label for="login">Login:</label>
						<input type="text" id="login" name="login" required />
					</div>
					<div class="form-group">
						<label for="password">Password:</label>
						<input
							type="password"
							id="password"
							name="password"
							required />
					</div>
					<div class="form-group">
						<label for="server">Server:</label>
						<input type="text" id="server" name="server" required />
					</div>
					<div class="form-group">
						<label for="deposit">Deposit per set:</label>
						<input
							type="text"
							id="deposit"
							name="deposit"
							required />
					</div>
					<div id="newTerminalContainer">
						<div class="form-group terminal-input">
							<label for="terminalFilePath"
								>Terminal File Path:</label
							>
							<input
								type="text"
								id="terminalFilePath"
								name="terminalFilePath"
								required />
							<button
								type="button"
								onclick="removeTerminal(this)">
								Remove
							</button>
						</div>
					</div>
					<button id="addNewTerminal">Add New Terminal</button>
					<div id="maxSets">Maximum Sets: 100</div>
					<div class="form-group">
						<label for="type">Type:</label>
						<select id="type" name="type" required>
							<option value="master">Master</option>
							<option value="slave">Slave</option>
						</select>
					</div>
					<div class="form-group">
						<button type="submit">Create Account</button>
					</div>
				</form>
			</section>
		</div>
	</main>
		<script>
			let maxSets = 100;

			document
				.getElementById("addNewTerminal")
				.addEventListener("click", function () {
					addNewTerminal();
				});

			function addNewTerminal() {
				maxSets += 100;
				const terminalContainer = document.getElementById(
					"newTerminalContainer"
				);
				const newTerminalInput = document.createElement("div");
				newTerminalInput.className = "form-group terminal-input";

				newTerminalInput.innerHTML = `
				   <label for="terminalFilePath">Terminal File Path:</label>
				   <input type="text" name="terminalFilePath" required />
				   <button type="button" onclick="removeTerminal(this)">Remove</button>
			    `;

				terminalContainer.appendChild(newTerminalInput);
				updateMaxSets();
			}

			function removeTerminal(button) {
				const terminalContainer = document.getElementById(
					"newTerminalContainer"
				);
				terminalContainer.removeChild(button.parentNode);
				maxSets -= 100;
				updateMaxSets();
			}

			function updateMaxSets() {
				document.getElementById(
					"maxSets"
				).textContent = `Maximum Sets: ${maxSets}`;
			}
		</script>
		<script src="{{url_for('static', filename='test.js')}}"></script>
	</body>
</html>

app/templates/error_log.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Dashboard</title>
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='styles.css') }}"
		/>
	</head>
	<body>
		<div class="container">
			<header>
				<h1>Error Log</h1>
				<a href="/"><button>Back to Dashboard</button></a>
			</header>

			<section class="error-section">
				<!-- Display errors as a string -->
				{{ errors }}
			</section>
		</div>
		<script src="{{url_for('static', filename='indexScript.js')}}"></script>
	</body>
</html>